FROM registry.redhat.io/ubi9/ubi

RUN dnf install -y python3 python3-pip && dnf clean all

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Start Uvicorn with proper host header support
CMD ["uvicorn", "sos_parser:app", "--host", "0.0.0.0", "--port", "8000", "--host-header", "localhost:8000"]